### ISSUE TITLE
About notifications

### ISSUE THREAD

**Issue by M-Falken** [ticgal/taskdrop#1]
Hi, and thanks for this plugin really useful for me.

Just some questions about the notifications:
1. We drop a task on the planning
2. A "New task" notification is sent.
3. And we always need to move or drag to adjust the hours.
4. So an "Update Task" notification is sent also.

And so on, you can easily understand that a tons of notifications would be sent just because of several adjustments of hours placement.

I wonder if it could be possible to have something like:
_First one_
1. We drag a task on the planning
2. We drop it and at this time a popup ask "Do you want to send notification now ?": yes/no
3. We adjust on hours or move it, and the popup again, and so on.

But this one could be very annoying indeed

_Second one_

Keep a check box in front of each row where were the tasks that were dropped on the schedule
So all tasks are now planned and ok with hours.
We can now tick all those for which we want to send notifications.
And click a button to send.
So the row now show "Notification sent" for 5 seconds and disappear.
The others still there and show "Notification not sent".

Hope I'm clear enough, what do you think of this suggestion ?
I can do a screenshot for that to better show you the idea.

Thanks for reading

**Comment by OscarBeiro** [comment]
Hi M-Falken,

I think I get what you mean, but let me explain what the plugin does.
Task'n'drop only lists un planned, to do tasks and reminders allowing you to drag'n'drop them.
Once they are dropped in the planning view, GLPI core behavior is back on. 

So this is what happens when you  plan any task in the usual way and drag'n'drop it or resize tasks to increase the duration.

Task update notification feature is a bit overkill in my opinion.

I understand your frustration but IMO your request is out of the scope of the plugin.

Regards,

**Comment by M-Falken** [comment]
Understood, but in usual way we set hours in advance on the task so the notification sent for new task is ok.
I agree for resize.
