### ISSUE TITLE
Change tasks not visible in to be planned

### ISSUE THREAD

**Issue by Geo-Ron** [ticgal/taskdrop#3]
Hi all,

Change tasks are not showing up. Is this by design?

**Comment by OscarBeiro** [comment]
Hi,
This plugin was a client request who allowed us to release it to the community.
If you want to increase its functionality, it should be sponsored.
Anyway, I would recommend you to wait until the release of GLPI 9.5 since there are some significant improvements in this area and this feature be already implemented.
Regards,

**Comment by miguelalves47** [comment]
Hi there,

I cant also drag and drop activity of users cause they are not appearing to me on plan this task. I just installed the plug in. Is not working

Any help?

Thanks

**Comment by OscarBeiro** [comment]
Olá Miguel,

I don't understand your issue. If it is related to Change tasks, they are not yet implemented for lack of sponsoring.

If it is another issue, please open a new one and add relevant information, GLPI version, OS,  screenshots, How to reproduce.

Thanks,
